// Material 3 palette ported from src/gateway/gui/frontend/index.html's inline
// tailwind.config. Single source of truth for both mobile (NativeWind) and
// web (Vite) Tailwind configs — see ../../tailwind.preset.cjs.
module.exports = {
  colors: {
    'on-tertiary-fixed-variant': '#3f484f',
    'primary-fixed': '#80f7dc',
    'on-tertiary': '#ffffff',
    'inverse-surface': '#2d3135',
    'secondary-container': '#e0e3e5',
    'primary-container': '#14a38b',
    'on-background': '#181c20',
    error: '#ba1a1a',
    'surface-tint': '#006b5a',
    'on-primary-fixed': '#00201a',
    'on-primary-container': '#003028',
    'on-error-container': '#93000a',
    'on-secondary-fixed-variant': '#444749',
    'tertiary-fixed-dim': '#bfc8d0',
    'on-secondary': '#ffffff',
    'secondary-fixed-dim': '#c4c7c9',
    'on-surface': '#181c20',
    'tertiary-container': '#89929a',
    'on-tertiary-fixed': '#141d23',
    'inverse-on-surface': '#eef1f6',
    'inverse-primary': '#62dac0',
    'surface-variant': '#e0e3e8',
    'on-error': '#ffffff',
    'on-secondary-container': '#626567',
    'tertiary-fixed': '#dbe4ed',
    primary: '#006b5a',
    'outline-variant': '#bccac4',
    secondary: '#5c5f61',
    'on-tertiary-container': '#222b32',
    background: '#f7f9ff',
    'surface-bright': '#f7f9ff',
    'surface-container-high': '#e5e8ee',
    outline: '#6d7a75',
    'surface-container-lowest': '#ffffff',
    'surface-dim': '#d7dadf',
    'on-secondary-fixed': '#191c1e',
    'surface-container-highest': '#e0e3e8',
    'error-container': '#ffdad6',
    tertiary: '#575f67',
    'on-primary-fixed-variant': '#005144',
    'primary-fixed-dim': '#62dac0',
    'surface-container': '#ebeef3',
    'on-primary': '#ffffff',
    'secondary-fixed': '#e0e3e5',
    'surface-container-low': '#f1f4f9',
    surface: '#f7f9ff',
    'on-surface-variant': '#3d4945',
    // Not part of the Material3 export — ported from style.css's --warning,
    // used for "pending" status indicators (e.g. staged action cards).
    warning: '#f59e0b',
  },
  borderRadius: {
    DEFAULT: '0.25rem',
    lg: '0.5rem',
    xl: '0.75rem',
    full: '9999px',
  },
  spacing: {
    gutter: '12px',
    base: '4px',
    sm: '12px',
    md: '16px',
    xs: '8px',
    xl: '32px',
    margin: '16px',
    lg: '24px',
  },
  fontFamily: {
    'mono-label': ['JetBrains Mono'],
    'label-sm': ['Hanken Grotesk'],
    'headline-lg': ['Hanken Grotesk'],
    'headline-md': ['Hanken Grotesk'],
    'label-caps': ['Hanken Grotesk'],
    'body-sm': ['Hanken Grotesk'],
    'body-md': ['Hanken Grotesk'],
  },
  fontSize: {
    'mono-label': ['11px', { lineHeight: '1', fontWeight: '500' }],
    'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
    'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
    'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
    'label-caps': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '700' }],
    'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
    'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
  },
};
