#!/usr/bin/env node
/**
 * Peekaboo CLI — bootstrap and manage a Peekaboo installation.
 *
 * Usage:
 *   npx peekaboo init [app-name]    Bootstrap a new installation
 *   npx peekaboo start              Start the server in the background
 *   npx peekaboo stop               Stop the background server
 *   npx peekaboo status             Check if the server is running
 */

import { randomBytes, randomUUID } from 'node:crypto';
import { existsSync, writeFileSync, readFileSync, unlinkSync, mkdirSync, realpathSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve, join } from 'node:path';
import { homedir } from 'node:os';
import { spawn } from 'node:child_process';
import { hashSync } from 'bcryptjs';
import { getDb } from './db/db.js';

// --- Credentials file path ---

export const CREDENTIALS_DIR = join(homedir(), '.peekaboo');
export const CREDENTIALS_PATH = join(CREDENTIALS_DIR, 'credentials.json');
const PID_PATH = join(CREDENTIALS_DIR, 'server.pid');

export interface Credentials {
  hubUrl: string;
  apiKey: string;
  hubDir: string;
}

/**
 * Write credentials to ~/.peekaboo/credentials.json.
 * Creates the directory if it doesn't exist.
 */
export function writeCredentials(creds: Credentials): void {
  mkdirSync(CREDENTIALS_DIR, { recursive: true });
  writeFileSync(CREDENTIALS_PATH, JSON.stringify(creds, null, 2) + '\n', 'utf-8');
}

/**
 * Read credentials from ~/.peekaboo/credentials.json.
 * Returns null if the file doesn't exist or is malformed.
 */
export function readCredentials(): Credentials | null {
  try {
    if (!existsSync(CREDENTIALS_PATH)) return null;
    const raw = readFileSync(CREDENTIALS_PATH, 'utf-8');
    const parsed = JSON.parse(raw);
    if (parsed.hubUrl && parsed.apiKey) return parsed as Credentials;
    return null;
  } catch {
    return null;
  }
}

// --- Init ---

export interface InitResult {
  secret: string;
  apiKey: string;
  dbPath: string;
  configPath: string;
  envPath: string;
  credentialsPath: string;
}

export interface InitOptions {
  appName?: string;
  port?: number;
}

/**
 * Bootstrap a new Peekaboo installation.
 *
 * Generates a master secret, writes .env and hub-config.yaml,
 * initializes the database, creates the first API key,
 * and writes credentials to ~/.peekaboo/credentials.json.
 */
export function init(targetDir?: string, options?: InitOptions): InitResult {
  const dir = targetDir ?? process.cwd();
  const envPath = resolve(dir, '.env');
  const configPath = resolve(dir, 'hub-config.yaml');
  const dbPath = resolve(dir, 'peekaboo.db');

  // Guard against re-initialization
  if (existsSync(envPath)) {
    throw new Error(`.env already exists at ${envPath}. Delete it first to re-initialize.`);
  }

  // Generate master secret
  const secret = randomBytes(32).toString('base64');

  // Write .env
  writeFileSync(envPath, `PEEKABOO_SECRET=${secret}\n`, 'utf-8');

  // Write minimal hub-config.yaml
  const port = options?.port ?? 3000;
  const configContent = [
    '# Peekaboo Hub Configuration',
    '# Generated by: npx peekaboo init',
    '#',
    `# Connect data sources through the GUI at http://localhost:${port}`,
    '',
    'sources: {}',
    '',
    `port: ${port}`,
    '',
  ].join('\n');
  writeFileSync(configPath, configContent, 'utf-8');

  // Initialize database
  const db = getDb(dbPath);

  // Generate API key
  const appName = options?.appName ?? 'default';
  const id = appName.toLowerCase().replace(/\s+/g, '-');
  const rawKey = `pk_${randomUUID().replace(/-/g, '')}`;
  const keyHash = hashSync(rawKey, 10);
  db.prepare(
    'INSERT INTO api_keys (id, key_hash, name, allowed_manifests) VALUES (?, ?, ?, ?)',
  ).run(id, keyHash, appName, JSON.stringify(['*']));

  db.close();

  // Write credentials file for auto-discovery by agents
  const hubUrl = `http://localhost:${port}`;
  writeCredentials({ hubUrl, apiKey: rawKey, hubDir: dir });

  return { secret, apiKey: rawKey, dbPath, configPath, envPath, credentialsPath: CREDENTIALS_PATH };
}

// --- Start / Stop / Status ---

/**
 * Start the Peekaboo server in the background.
 * Spawns a detached node process and writes the PID to ~/.peekaboo/server.pid.
 */
export function startBackground(hubDir?: string): { pid: number; hubDir: string } {
  const dir = hubDir ?? readCredentials()?.hubDir ?? process.cwd();
  const indexPath = resolve(dir, 'dist', 'index.js');

  if (!existsSync(indexPath)) {
    throw new Error(`Server entry not found at ${indexPath}. Run 'pnpm build' first.`);
  }

  // Check if already running
  const existing = getServerPid();
  if (existing !== null) {
    try {
      process.kill(existing, 0); // Check if process exists
      throw new Error(`Server is already running (PID ${existing}). Run 'npx peekaboo stop' first.`);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== 'ESRCH') throw err;
      // Process doesn't exist, stale PID file — clean up
    }
  }

  const child = spawn('node', [indexPath], {
    cwd: dir,
    detached: true,
    stdio: 'ignore',
    env: { ...process.env },
  });

  child.unref();

  const pid = child.pid!;
  mkdirSync(CREDENTIALS_DIR, { recursive: true });
  writeFileSync(PID_PATH, String(pid), 'utf-8');

  return { pid, hubDir: dir };
}

/**
 * Stop the background Peekaboo server.
 */
export function stopBackground(): boolean {
  const pid = getServerPid();
  if (pid === null) return false;

  try {
    process.kill(pid, 'SIGTERM');
  } catch {
    // Process already gone
  }

  try { unlinkSync(PID_PATH); } catch { /* ignore */ }
  return true;
}

/**
 * Get the PID of the background server, or null if not running.
 */
export function getServerPid(): number | null {
  try {
    if (!existsSync(PID_PATH)) return null;
    const pid = parseInt(readFileSync(PID_PATH, 'utf-8').trim(), 10);
    if (isNaN(pid)) return null;
    process.kill(pid, 0); // Check if process exists
    return pid;
  } catch {
    return null;
  }
}

// --- CLI runner (only executes when this file is the entry point) ---
// Resolve symlinks so this works with npx (which symlinks node_modules/.bin/peekaboo → dist/cli.js)
const isDirectRun = (() => {
  try {
    const self = fileURLToPath(import.meta.url);
    const invoked = realpathSync(process.argv[1]);
    return invoked === self;
  } catch {
    return false;
  }
})();

if (isDirectRun) {
  const command = process.argv[2];

  if (command === 'init') {
    const appName = process.argv[3] ?? 'default';
    try {
      const result = init(undefined, { appName });
      console.log('\n  Peekaboo initialized successfully!\n');
      console.log(`  .env created            ${result.envPath}`);
      console.log(`  hub-config.yaml created  ${result.configPath}`);
      console.log(`  Database created         ${result.dbPath}`);
      console.log(`  Credentials saved        ${result.credentialsPath}`);
      console.log(`\n  API Key (used by agents to call the hub):`);
      console.log(`    ${result.apiKey}\n`);
      console.log('  Next steps:');
      console.log('    1. Start the server:  npx peekaboo start');
      console.log('    2. Open the GUI:      http://localhost:3000');
      console.log('    3. Connect sources and configure access policies\n');
    } catch (err) {
      console.error(`Error: ${(err as Error).message}`);
      process.exit(1);
    }
  } else if (command === 'start') {
    try {
      const result = startBackground();
      console.log(`\n  Peekaboo server started in background (PID ${result.pid})`);
      console.log(`  Hub directory: ${result.hubDir}`);
      console.log(`  GUI: http://localhost:3000\n`);
    } catch (err) {
      console.error(`Error: ${(err as Error).message}`);
      process.exit(1);
    }
  } else if (command === 'stop') {
    if (stopBackground()) {
      console.log('\n  Peekaboo server stopped.\n');
    } else {
      console.log('\n  No running Peekaboo server found.\n');
    }
  } else if (command === 'status') {
    const pid = getServerPid();
    if (pid !== null) {
      console.log(`\n  Peekaboo server is running (PID ${pid})\n`);
    } else {
      console.log('\n  Peekaboo server is not running.\n');
    }
  } else {
    console.log('Peekaboo CLI v0.1.0');
    console.log('\nUsage:');
    console.log('  npx peekaboo init [app-name]   Bootstrap a new Peekaboo installation');
    console.log('  npx peekaboo start             Start the server in the background');
    console.log('  npx peekaboo stop              Stop the background server');
    console.log('  npx peekaboo status            Check if the server is running');
  }
}
